# Generated by Django 5.2.4 on 2025-07-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('client_email', models.CharField(unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
