# Generated by Django 5.2 on 2025-07-11 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('mobno', models.CharField(blank=True, max_length=15, null=True)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('evaluation_purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_id', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user_roles', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('client_id', models.CharField(blank=True, max_length=20, null=True)),
                ('salary_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('company_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('financial_year', models.CharField(blank=True, max_length=9, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('probation_date', models.DateField(blank=True, null=True)),
                ('employee_status', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
