# Generated by Django 5.2.4 on 2025-07-18 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('joining_data', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('ph_no', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_id', models.CharField(blank=True, max_length=100, null=True)),
                ('evaluation_pourpos', models.TextField(blank=True, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user_role', models.JSONField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('salary_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('company_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('financial_year', models.CharField(blank=True, max_length=10, null=True)),
                ('probation_date', models.DateField(blank=True, null=True)),
                ('employee_status', models.CharField(blank=True, max_length=50, null=True)),
                ('manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
