# Generated by Django 5.2.4 on 2025-07-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='joining_data',
            new_name='joining_date',
        ),
    ]
