# Generated by Django 5.2.4 on 2025-07-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0002_rename_joining_data_master_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='user_role',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
